api_platform:
    title: 'Boardgame REST API'
    description: 'A Symfony API to manage a simple bordgame app.'
    version: '1.0.2'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
